import { ButtonStyle } from "discord.js";

export const PermissionsTranslate = {
    AddReactions: "Adicionar reações",
    Administrator: "Administrador",
    AttachFiles: "Anexar arquivos",
    BanMembers: "Banir membros",
    ChangeNickname: "Alterar apelido",
    Connect: "Conectar",
    CreateInstantInvite: "Criar convite",
    CreatePrivateThreads: "Criar tópicos privados",
    CreatePublicThreads: "Criar tópicos públicos",
    DeafenMembers: "Ensurdecer membros",
    EmbedLinks: "Inserir links",
    KickMembers: "Expulsar membros",
    ManageChannels: "Gerenciar canais",
    ManageEmojisAndStickers: "Gerenciar emojis e figurinhas",
    ManageEvents: "Gerenciar eventos",
    ManageGuild: "Gerenciar servidor",
    ManageMessages: "Gerenciar mensagens",
    ManageNicknames: "Gerenciar apelidos",
    ManageRoles: "Gerenciar cargos",
    ManageThreads: "Gerenciar tópicos",
    ManageWebhooks: "Gerenciar webhooks",
    MentionEveryone: "Mencionar everyone, here, e todos os cargos",
    ModerateMembers: "Membros de castigo",
    MoveMembers: "Mover membros",
    MuteMembers: "Silenciar membros",
    PrioritySpeaker: "Voz prioritária",
    ReadMessageHistory: "Ver histórico de mensagens",
    RequestToSpeak: "Pedir para falar",
    SendMessages: "Enviar mensagens",
    SendMessagesInThreads: "Enviar mensagens em tópicos",
    SendTTSMessages: "Enviar mensagens em Texto-para-voz",
    Speak: "Falar",
    UseEmbeddedActivities: "Começar atividades",
    Stream: "Transmitir Tela",
    UseApplicationCommands: "Usar comandos de aplicativo",
    UseExternalEmojis: "Usar emojis externos",
    UseExternalStickers: "Usar figurinhas externas",
    UseVAD: "Usar detecção de voz",
    ViewAuditLog: "Ver o registro de auditoria",
    ViewChannel: "Ver canais",
    ViewGuildInsights: "Ver Análises do servidor",
    UseSoundboard: "Usar sons em call",
    UseExternalSounds: "User sons externos",
    SendVoiceMessages: "Mandar Audios",
    CreateGuildExpressions: "Criar Expressões do Servidor",
    CreateEvents: "Criar Eventos"
};

export const urls = {
    saphireSiteUrl: "https://saphire.one",
    saphireApiUrl: "https://api.saphire.one",
    clientInvite: (clientId: string) => `https://discord.com/oauth2/authorize?client_id=${clientId}`,
    not_found_image: "https://i.pinimg.com/originals/36/72/34/36723405ae6788b18a972c68ce414b04.gif",
    twitch_logo: "https://freelogopng.com/images/all_img/1656152623twitch-logo-round.png",
    cdn: (bucket: "countries" | "characters" | "brands" | "saphire", pathname: string) => `https://cdn.saphire.one/${bucket}/${pathname}`
};

export const Config = {
    locales: ["de", "en-US", "es-ES", "fr", "ja", "pt-BR", "zh-CN"],
    flagLocales: {

        de: "🇩🇪",
        german: "🇩🇪",

        "en-US": "🇺🇸",
        english: "🇺🇸",

        "es-ES": "🇪🇸",
        spanish: "🇪🇸",

        fr: "🇫🇷",
        french: "🇫🇷",

        ja: "🇯🇵",
        japanese: "🇯🇵",

        "pt-BR": "🇧🇷",
        portuguese: "🇧🇷",

        "zh-CN": "🇨🇳",
        chinese: "🇨🇳"
    },
    shardList: [...new Array(Math.floor(Math.random() * 15) + 1).keys()],
    ownerId: "451619591320371213",
    Andre: "648389538703736833",
    designerId: "830226550116057149",
    clientId: "837147659898191902",
    saphireApiId: "1035037311907405834",
    statusChannelNotification: "1036298713691328614",
    charactersQuizSuggestChannel: "1224055344905453588",
    guildId: "952214872584749056",
    guildPackageId: "882475447387054081",
    logomarcaIndicateChannelId: "995151748148768839",
    balaceReportChannelId: "1031388957151330344",
    BugsChannelId: "1007819488584028180",
    LogChannelId: "993893182951673860",
    PackageInvite: "https://discord.gg/UArp6eyvwu",
    MoonServerLink: "https://discord.gg/2EMVCbJxuC",
    SaphiDocs: "https://saphire.gitbook.io/saphire/",
    TopGGLink: "https://top.gg/bot/912509487984812043/vote",
    Terms: "https://saphire.gitbook.io/saphire/saphire/termos-de-servicos",
    QrCodeWithoutPrice: "https://media.discordapp.net/attachments/893361065084198954/1007101315832360970/WhatsApp_Image_2022-08-10_at_10.39.05_PM.jpeg",
    ErrorWebhookProfileIcon: "https://media.discordapp.net/attachments/893361065084198954/1007839310772449400/Saphire_Panic.png",
    PackageLogsWebhookProfileIcon: "https://media.discordapp.net/attachments/893361065084198954/1018699630998986752/data-management.png?width=484&height=484",
    RefundSystemIcon: "https://media.discordapp.net/attachments/893361065084198954/1028707418789642300/refund.png?width=473&height=473",
    WebhookJokempoIcon: "https://media.discordapp.net/attachments/893361065084198954/1090834486461210686/pedra.png?width=468&height=468",
    webhookAnimeReporter: undefined,
    webhookQuizReporter: undefined,
    vocePrefereChannel: "1018945013016690708",
    questionSuggestionsSave: "1082424705832718446",
    guildsToPrivateCommands: [
        "986292524790464562", // Emoji Package
        "888464632291917956", // Sunshine Dreamer
        "882475447387054081", // Package da Saphire
        "952214872584749056", // Saphire's Hub
        "1128713242693349466" // Bunker Central Community
    ],
    SpotifyAccessToken: "",
    TwitchAccessToken: ""
};

export const ChannelsTypes = {
    0: "Canal de Texto",
    1: "Mensagens Direta / Privado",
    2: "Canal de Voz",
    3: "Grupo Privado",
    4: "Categoria",
    5: "Canal de Anúncios",
    10: "Canal de Anúncios Temporário (Thread)",
    11: "Canal Público (Thread)",
    12: "Canal Privado (Thread)",
    13: "Canal de Palco",
    14: "Canal de Diretoria (Studant Hub)",
    15: "Canal de Fórum"
};

export const DiscordColors = {
    Default: "Padrão",
    Invisible: "Invisível",
    White: "Branco",
    Aqua: "Água",
    Green: "Verde",
    Blue: "Azul",
    Yellow: "Amarelo",
    Purple: "Roxo",
    LuminousVividPink: "Rosa Vívido Luminoso",
    Fuchsia: "Fuchsia",
    Gold: "Ouro",
    Orange: "Laranja",
    Red: "Vermelho",
    Grey: "Cinza",
    Navy: "Oceano Apagado",
    DarkAqua: "Água Escura",
    DarkGreen: "Verde Escuro",
    DarkBlue: "Azul Escuro",
    DarkPurple: "Roxo Escuro",
    DarkVividPink: "Rosa Vívido Escuro",
    DarkGold: "Ouro Escuro",
    DarkOrange: "Laranja Escuro",
    DarkRed: "Vermelho Escuro",
    DarkGrey: "Cinza Escuro",
    DarkerGrey: "Cinza Mais Escuro",
    LightGrey: "Cinza Claro",
    DarkNavy: "Oceano Escuro",
    Blurple: "Violeta",
    Greyple: "Verde Acinzentado",
    DarkButNotBlack: "Escuro, mas não preto",
    NotQuiteBlack: "Não tão preto",
    LuminousVividRed: "Vermelho Vívido Luminoso"
};

export const BitColors = {
    Default: 0x000000,
    Invisible: 0x2b2d31,
    White: 0xffffff,
    Aqua: 0x1abc9c,
    Green: 0x57f287,
    Blue: 0x3498db,
    Yellow: 0xfee75c,
    Purple: 0x9b59b6,
    LuminousVividPink: 0xe91e63,
    Fuchsia: 0xeb459e,
    Gold: 0xf1c40f,
    Orange: 0xe67e22,
    Red: 0xed4245,
    Grey: 0x95a5a6,
    Navy: 0x34495e,
    DarkAqua: 0x11806a,
    DarkGreen: 0x1f8b4c,
    DarkBlue: 0x206694,
    DarkPurple: 0x71368a,
    DarkVividPink: 0xad1457,
    DarkGold: 0xc27c0e,
    DarkOrange: 0xa84300,
    DarkRed: 0x992d22,
    DarkGrey: 0x979c9f,
    DarkerGrey: 0x7f8c8d,
    LightGrey: 0xbcc0c0,
    DarkNavy: 0x2c3e50,
    Blurple: 0x5865f2,
    Greyple: 0x99aab5,
    DarkButNotBlack: 0x2c2f33,
    NotQuiteBlack: 0x23272a,
    LuminousVividRed: 0xff0000
};

export const HexColors = {
    Default: "#000000",
    Invisible: "#2b2d31",
    White: "#ffffff",
    Aqua: "#1abc9c",
    Green: "#57f287",
    Blue: "#3498db",
    Yellow: "#fee75c",
    Purple: "#9b59b6",
    LuminousVividPink: "#e91e63",
    Fuchsia: "#eb459e",
    Gold: "#f1c40f",
    Orange: "#e67e22",
    Red: "#ed4245",
    Grey: "#95a5a6",
    Navy: "#34495e",
    DarkAqua: "#11806a",
    DarkGreen: "#1f8b4c",
    DarkBlue: "#206694",
    DarkPurple: "#71368a",
    DarkVividPink: "#ad1457",
    DarkGold: "#c27c0e",
    DarkOrange: "#a84300",
    DarkRed: "#992d22",
    DarkGrey: "#979c9f",
    DarkerGrey: "#7f8c8d",
    LightGrey: "#bcc0c0",
    DarkNavy: "#2c3e50",
    Blurple: "#5865f2",
    Greyple: "#99aab5",
    DarkButNotBlack: "#2c2f33",
    NotQuiteBlack: "#23272a",
    LuminousVividRed: "#ff0000"
};

export const Languages = {
    af: "Africano",
    am: "Amárico",
    ar: "Arábico",
    az: "Azerbaijano",
    be: "Bielorrusso",
    bg: "Bulgariano",
    bn: "Bengali",
    bs: "Bosniano",
    ca: "Catalano",
    ceb: "Cebuano",
    co: "Corso",
    cs: "Tcheco",
    cy: "Galês",
    da: "Dinamarquês",
    de: "Alemão",
    el: "Grego",
    en: "Inglês",
    eo: "Esperanto",
    es: "Espanhol",
    et: "Estoniano",
    eu: "Basco",
    fa: "Persa",
    fi: "Finlandês",
    fr: "Francês",
    fy: "Frísio",
    ga: "Irlandês",
    gd: "Scots Gaelic",
    gl: "Gaélico Escocês",
    gu: "Gujarati",
    ha: "Hauçá",
    haw: "Hawaiano",
    he: "Hebraico",
    hi: "Hindi",
    hmn: "Hmong",
    hr: "Croata",
    ht: "Crioulo Haitiano",
    hu: "Húngaro",
    hy: "Armênio",
    id: "Indonésio",
    ig: "Ibo",
    is: "Islandês",
    it: "Italiano",
    iw: "Hebraico Antigo",
    ja: "Japonês",
    jw: "Javanês",
    ka: "Georgiano",
    kk: "Cazaque",
    km: "Khmer",
    kn: "Canarês",
    ko: "Koreano",
    ku: "Curdo (Kurmanji)",
    ky: "Quirguistão",
    la: "Latin",
    lb: "Luxemburguês",
    lo: "Laos",
    lt: "Lituano",
    lv: "Letão",
    mg: "Malgaxe",
    mi: "Maori",
    mk: "Macedônio",
    ml: "Malaiala",
    mn: "Mongol",
    mr: "Marathi",
    ms: "Malaio",
    mt: "Maltês",
    my: "Mianmar (Burmese)",
    ne: "Nepalês",
    nl: "Holandês",
    no: "Norueguês",
    ny: "Chichewa",
    pa: "Chichewa",
    pl: "Polonês",
    ps: "Pashto",
    pt: "Português",
    ro: "Romeno",
    ru: "Russo",
    sd: "Sindi",
    si: "Cingalês",
    sk: "Eslovaco",
    sl: "Esloveno",
    sm: "Samoano",
    sn: "Shona",
    so: "Somali",
    sq: "Albanês",
    sr: "Sérvio",
    st: "Sesotho",
    su: "Sundanês",
    sv: "Sueco",
    sw: "Suaíli",
    ta: "Tâmil",
    te: "Telugu",
    tg: "Tadjique",
    th: "Tailandês",
    tl: "Filipino",
    tr: "Turco",
    uk: "Ucraniano",
    ur: "Urdu",
    uz: "Uzbeque",
    vi: "Vietnamita",
    xh: "Xhosa",
    yi: "Iídiche",
    yo: "Iorubá",
    zu: "Zulu",
};

export const UserFlags = {
    "1": "Staff",
    "2": "Partner",
    "4": "Hypesquad",
    "8": "BugHunterLevel1",
    "16": "MFASMS",
    "32": "PremiumPromoDismissed",
    "64": "HypeSquadOnlineHouse1",
    "128": "HypeSquadOnlineHouse2",
    "256": "HypeSquadOnlineHouse3",
    "512": "PremiumEarlySupporter",
    "1024": "TeamPseudoUser",
    "8192": "HasUnreadUrgentMessages",
    "16384": "BugHunterLevel2",
    "65536": "VerifiedBot",
    "131072": "VerifiedDeveloper",
    "262144": "CertifiedModerator",
    "524288": "BotHTTPInteractions",
    "1048576": "Spammer",
    "2097152": "DisablePremium",
    "4194304": "ActiveDeveloper",
    "17592186044416": "Quarantined",
    "1125899906842624": "Collaborator",
    "2251799813685248": "RestrictedCollaborator"
};

export const Flags = {
    BotHTTPInteractions: "Bot de integração via HTTP",
    BugHunterLevel1: "Bug Hunter Level 1",
    BugHunterLevel2: "Bug Hunter Level 2",
    CertifiedModerator: "Moderador certificado pelo Discord",
    Hypesquad: "Membro do evento HypeSquad",
    HypeSquadOnlineHouse1: "Membro da House Bravery",
    HypeSquadOnlineHouse2: "Membro da House Brilliance",
    HypeSquadOnlineHouse3: "Membro da House Balance",
    ActiveDeveloper: "Desenvolvedor(a) Ativo",
    Partner: "Proprietário de Servidor parceiro",
    PremiumEarlySupporter: "Apoiador Inicial",
    Quarantined: "Usuário em quarentena por atos recentes",
    Spammer: "Usuário punido por spam",
    Staff: "Empregado do Discord",
    TeamPseudoUser: "Usuário é uma equipe",
    VerifiedBot: "Bot Verificado",
    System: "Sistema",
    VerifiedDeveloper: "Desenvolvedor de bot inicial",

    MFASMS: "OAUTH SMS",
    PremiumPromoDismissed: "Nitro Perdido",
    HasUnreadUrgentMessages: "Mensagem urgente não lida",
    DisablePremium: "Premium Disativado",
    Collaborator: "Colaborador",
    RestrictedCollaborator: "Colaborador Restrito",
};

export const PermissionsAsFlagBits = {
    CreateInstantInvite: 1,
    KickMembers: 2,
    BanMembers: 4,
    Administrator: 8,
    ManageChannels: 16,
    ManageGuild: 32,
    AddReactions: 64,
    ViewAuditLog: 128,
    PrioritySpeaker: 256,
    Stream: 512,
    ViewChannel: 1024,
    SendMessages: 2048,
    SendTTSMessages: 4096,
    ManageMessages: 8192,
    EmbedLinks: 16384,
    AttachFiles: 32768,
    ReadMessageHistory: 65536,
    MentionEveryone: 131072,
    UseExternalEmojis: 262144,
    ViewGuildInsights: 524288,
    Connect: 1048576,
    Speak: 2097152,
    MuteMembers: 4194304,
    DeafenMembers: 8388608,
    MoveMembers: 16777216,
    UseVAD: 33554432,
    ChangeNickname: 67108864,
    ManageNicknames: 134217728,
    ManageRoles: 268435456,
    ManageWebhooks: 536870912,
    ManageEmojisAndStickers: 1073741824,
    UseApplicationCommands: 2147483648,
    RequestToSpeak: 4294967296,
    ManageEvents: 8589934592,
    ManageThreads: 17179869184,
    CreatePublicThreads: 34359738368,
    CreatePrivateThreads: 68719476736,
    UseExternalStickers: 137438953472,
    SendMessagesInThreads: 274877906944,
    UseEmbeddedActivities: 549755813888,
    ModerateMembers: 1099511627776
};

export const PermissionsBitToString = {
    1: "CreateInstantInvite",
    2: "KickMembers",
    4: "BanMembers",
    8: "Administrator",
    16: "ManageChannels",
    32: "ManageGuild",
    64: "AddReactions",
    128: "ViewAuditLog",
    256: "PrioritySpeaker",
    512: "Stream",
    1024: "ViewChannel",
    2048: "SendMessages",
    4096: "SendTTSMessages",
    8192: "ManageMessages",
    16384: "EmbedLinks",
    32768: "AttachFiles",
    65536: "ReadMessageHistory",
    131072: "MentionEveryone",
    262144: "UseExternalEmojis",
    524288: "ViewGuildInsights",
    1048576: "Connect",
    2097152: "Speak",
    4194304: "MuteMembers",
    8388608: "DeafenMembers",
    16777216: "MoveMembers",
    33554432: "UseVAD",
    67108864: "ChangeNickname",
    134217728: "ManageNicknames",
    268435456: "ManageRoles",
    536870912: "ManageWebhooks",
    1073741824: "ManageEmojisAndStickers",
    2147483648: "UseApplicationCommands",
    4294967296: "RequestToSpeak",
    8589934592: "ManageEvents",
    17179869184: "ManageThreads",
    34359738368: "CreatePublicThreads",
    68719476736: "CreatePrivateThreads",
    137438953472: "UseExternalStickers",
    274877906944: "SendMessagesInThreads",
    549755813888: "UseEmbeddedActivities",
    1099511627776: "ModerateMembers"
};

export const DiscordPermissons = {
    AddReactions: "AddReactions",
    Administrator: "Administrator",
    AttachFiles: "AttachFiles",
    BanMembers: "BanMembers",
    ChangeNickname: "ChangeNickname",
    Connect: "Connect",
    CreateInstantInvite: "CreateInstantInvite",
    CreatePrivateThreads: "CreatePrivateThreads",
    CreatePublicThreads: "CreatePublicThreads",
    DeafenMembers: "DeafenMembers",
    EmbedLinks: "EmbedLinks",
    KickMembers: "KickMembers",
    ManageChannels: "ManageChannels",
    ManageEmojisAndStickers: "ManageEmojisAndStickers",
    ManageEvents: "ManageEvents",
    ManageGuild: "ManageGuild",
    ManageMessages: "ManageMessages",
    ManageNicknames: "ManageNicknames",
    ManageRoles: "ManageRoles",
    ManageThreads: "ManageThreads",
    ManageWebhooks: "ManageWebhooks",
    MentionEveryone: "MentionEveryone",
    ModerateMembers: "ModerateMembers",
    MoveMembers: "MoveMembers",
    MuteMembers: "MuteMembers",
    PrioritySpeaker: "PrioritySpeaker",
    ReadMessageHistory: "ReadMessageHistory",
    RequestToSpeak: "RequestToSpeak",
    SendMessages: "SendMessages",
    SendMessagesInThreads: "SendMessagesInThreads",
    SendTTSMessages: "SendTTSMessages",
    Speak: "Speak",
    UseEmbeddedActivities: "UseEmbeddedActivities",
    Stream: "Stream",
    UseApplicationCommands: "UseApplicationCommands",
    UseExternalEmojis: "UseExternalEmojis",
    UseExternalStickers: "UseExternalStickers",
    UseVAD: "UseVAD",
    ViewAuditLog: "ViewAuditLog",
    ViewChannel: "ViewChannel",
    ViewGuildInsights: "ViewGuildInsights",
    SendVoiceMessages: "SendVoiceMessages",
    CreateGuildExpressions: "CreateGuildExpressions",
    CreateEvents: "CreateEvents"
};

export const DiscordErrorsCode = {
    0: "General error",
    10001: "Unknown account",
    10002: "Unknown application",
    10003: "Unknown channel",
    10004: "Unknown guild",
    10005: "Unknown integration",
    10006: "Unknown invite",
    10007: "Unknown member",
    10008: "Unknown message",
    10009: "Unknown permission overwrite",
    10010: "Unknown provider",
    10011: "Unknown role",
    10012: "Unknown token",
    10013: "Unknown user",
    10014: "Unknown emoji",
    10015: "Unknown webhook",
    10016: "Unknown webhook service",
    10020: "Unknown session",
    10026: "Unknown ban",
    10027: "Unknown SKU",
    10028: "Unknown Store Listing",
    10029: "Unknown entitlement",
    10030: "Unknown build",
    10031: "Unknown lobby",
    10032: "Unknown branch",
    10033: "Unknown store directory layout",
    10036: "Unknown redistributable",
    10038: "Unknown gift code",
    10049: "Unknown stream",
    10050: "Unknown premium server subscribe cooldown",
    10057: "Unknown guild template",
    10059: "Unknown discoverable server category",
    10060: "Unknown sticker",
    10062: "Unknown interaction",
    10063: "Unknown application command",
    10065: "Unknown voice state",
    10066: "Unknown application command permissions",
    10067: "Unknown Stage Instance",
    10068: "Unknown Guild Member Verification Form",
    10069: "Unknown Guild Welcome Screen",
    10070: "Unknown Guild Scheduled Event",
    10071: "Unknown Guild Scheduled Event User",
    10087: "Unknown Tag",
    20001: "Bots cannot use this endpoint",
    20002: "Only bots can use this endpoint",
    20009: "Explicit content cannot be sent to the desired recipient(s)",
    20012: "You are not authorized to perform this action on this application",
    20016: "This action cannot be performed due to slowmode rate limit",
    20018: "Only the owner of this account can perform this action",
    20022: "This message cannot be edited due to announcement rate limits",
    20024: "Under minimum age",
    20028: "The channel you are writing has hit the write rate limit",
    20029: "The write action you are performing on the server has hit the write rate limit",
    20031: "Your Stage topic, server name, server description, or channel names contain words that are not allowed",
    20035: "Guild premium subscription level too low",
    30001: "Maximum number of guilds reached (100)",
    30002: "Maximum number of friends reached (1000)",
    30003: "Maximum number of pins reached for the channel (50)",
    30004: "Maximum number of recipients reached (10)",
    30005: "Maximum number of guild roles reached (250)",
    30007: "Maximum number of webhooks reached (10)",
    30008: "Maximum number of emojis reached",
    30010: "Maximum number of reactions reached (20)",
    30013: "Maximum number of guild channels reached (500)",
    30015: "Maximum number of attachments in a message reached (10)",
    30016: "Maximum number of invites reached (1000)",
    30018: "Maximum number of animated emojis reached",
    30019: "Maximum number of server members reached",
    30030: "Maximum number of server categories has been reached (5)",
    30031: "Guild already has a template",
    30032: "Maximum number of application commands reached",
    30033: "Max number of thread participants has been reached (1000)",
    30034: "Max number of daily application command creates has been reached (200)",
    30035: "Maximum number of bans for non-guild members have been exceeded",
    30037: "Maximum number of bans fetches has been reached",
    30038: "Maximum number of uncompleted guild scheduled events reached (100)",
    30039: "Maximum number of stickers reached",
    30040: "Maximum number of prune requests has been reached. Try again later",
    30042: "Maximum number of guild widget settings updates has been reached. Try again later",
    30046: "Maximum number of edits to messages older than 1 hour reached. Try again later",
    30047: "Maximum number of pinned threads in a forum channel has been reached",
    30048: "Maximum number of tags in a forum channel has been reached",
    30052: "Bitrate is too high for channel of this type",
    40001: "Unauthorized. Provide a valid token and try again",
    40002: "You need to verify your account in order to perform this action",
    40003: "You are opening direct messages too fast",
    40004: "Send messages has been temporarily disabled",
    40005: "Request entity too large. Try sending something smaller in size",
    40006: "This feature has been temporarily disabled server-side",
    40007: "The user is banned from this guild",
    40012: "Connection has been revoked",
    40032: "Target user is not connected to voice",
    40033: "This message has already been crossposted",
    40041: "An application command with that name already exists",
    40043: "Application interaction failed to send",
    40060: "Interaction has already been acknowledged",
    40061: "Tag names must be unique",
    50001: "Missing access",
    50002: "Invalid account type",
    50003: "Cannot execute action on a DM channel",
    50004: "Guild widget disabled",
    50005: "Cannot edit a message authored by another user",
    50006: "Cannot send an empty message",
    50007: "Cannot send messages to this user",
    50008: "Cannot send messages in a non-text channel",
    50009: "Channel verification level is too high for you to gain access",
    50010: "OAuth2 application does not have a bot",
    50011: "OAuth2 application limit reached",
    50012: "Invalid OAuth2 state",
    50013: "You lack permissions to perform that action",
    50014: "Invalid authentication token provided",
    50015: "Note was too long",
    50016: "Provided too few or too many messages to delete. Must provide at least 2 and fewer than 100 messages to delete",
    50017: "Invalid MFA Level",
    50019: "A message can only be pinned to the channel it was sent in",
    50020: "Invite code was either invalid or taken",
    50021: "Cannot execute action on a system message",
    50024: "Cannot execute action on this channel type",
    50025: "Invalid OAuth2 access token provided",
    50026: "Missing required OAuth2 scope",
    50027: "Invalid webhook token provided",
    50028: "Invalid role",
    50033: "Invalid Recipient(s)",
    50034: "A message provided was too old to bulk delete",
    50035: "Invalid form body (returned for both application/json and multipart/form-data bodies), or invalid Content-Type provided",
    50036: "An invite was accepted to a guild the application's bot is not in",
    50041: "Invalid API version provided",
    50045: "File uploaded exceeds the maximum size",
    50046: "Invalid file uploaded",
    50054: "Cannot self-redeem this gift",
    50055: "Invalid Guild",
    50068: "Invalid message type",
    50070: "Payment source required to redeem gift",
    50074: "Cannot delete a channel required for Community guilds",
    50080: "Cannot edit stickers within a message",
    50081: "Invalid sticker sent",
    50083: "Tried to perform an operation on an archived thread, such as editing a message or adding a user to the thread",
    50084: "Invalid thread notification settings",
    50085: "before value is earlier than the thread creation date",
    50086: "Community server channels must be text channels",
    50095: "This server is not available in your location",
    50097: "This server needs monetization enabled in order to perform this action",
    50101: "This server needs more boosts to perform this action",
    50109: "The request body contains invalid JSON.",
    50132: "Ownership cannot be transferred to a bot user",
    50138: "Failed to resize asset below the maximum size: 262144",
    50146: "Uploaded file not found.",
    50600: "You do not have permission to send this sticker.",
    60003: "Two factor is required for this operation",
    80004: "No users with DiscordTag exist",
    90001: "Reaction was blocked",
    110001: "Application not yet available. Try again later",
    130000: "API resource is currently overloaded. Try again a little later",
    150006: "The Stage is already open",
    160002: "Cannot reply without permission to read message history",
    160004: "A thread has already been created for this message",
    160005: "Thread is locked",
    160006: "Maximum number of active threads reached",
    160007: "Maximum number of active announcement threads reached",
    170001: "Invalid JSON for uploaded Lottie file",
    170002: "Uploaded Lotties cannot contain rasterized images such as PNG or JPEG",
    170003: "Sticker maximum framerate exceeded",
    170004: "Sticker frame count exceeds maximum of 1000 frames",
    170005: "Lottie animation maximum dimensions exceeded",
    170006: "Sticker frame rate is either too small or too large",
    170007: "Sticker animation duration exceeds maximum of 5 seconds",
    180000: "Cannot update a finished event",
    180002: "Failed to create stage needed for stage event",
    200000: "Message was blocked by automatic moderation",
    200001: "Title was blocked by automatic moderation",
    220003: "Webhooks can only create threads in forum channels"
};

export const ErrorsToIgnore = [
    // 10003, // "Unknown channel",
    // 10007, // "Unknown member",
    // 10008, // "Unknown message",
    // 10011, // "Unknown role",
    // 10013, // "Unknown user",
    // 10014, // "Unknown emoji",
    // 10026, // "Unknown ban",
    // 10060, // "Unknown sticker",
    10062, // "Unknown interaction",
    20035, // "Guild premium subscription level too low",
    30003, // "Maximum number of pins reached for the channel (50)",
    30005, // "Maximum number of guild roles reached (250)",
    30007, // "Maximum number of webhooks reached (10)",
    30008, // "Maximum number of emojis reached",
    30010, // "Maximum number of reactions reached (20)",
    30013, // "Maximum number of guild channels reached (500)",
    30018, // "Maximum number of animated emojis reached",
    30030, // "Maximum number of server categories has been reached (5)",
    30032, // "Maximum number of application commands reached",
    30033, // "Max number of thread participants has been reached (1000)",
    30034, // "Max number of daily application command creates has been reached (200)",
    30035, // "Maximum number of bans for non-guild members have been exceeded",
    30037, // "Maximum number of bans fetches has been reached",
    30039, // "Maximum number of stickers reached",
    50007, // "Cannot send messages to this user",
    50008, // "Cannot send messages in a non-text channel",
    50016, // "Provided too few or too many messages to delete. Must provide at least 2 and fewer than 100 messages to delete",
    50028, // "Invalid role",
    50034, // "A message provided was too old to bulk delete",
    50074, // "Cannot delete a channel required for Community guilds",
    50080, // "Cannot edit stickers within a message",
    50081 // "Invalid sticker sent"
];

export const ErrorResponse = {
    10003: "Canal desconhecido.",
    10007: "Membro desconhecido.",
    10008: "Mensagem desconhecida.",
    10011: "Cargo desconhecido.",
    10013: "Usuário desconhecido.",
    10014: "Emoji desconhecido.",
    10026: "Ban desconhecido.",
    10060: "Sticker desconhecido.",
    10062: "Interação desconhecida.",
    20035: "Nível de impulso insuficiente.",
    30003: "Número máximo de mensagens fixadas atingido. (50)",
    30005: "Número máximo de cargo criados atingido. (250)",
    30007: "Número máximo de webhooks criadas atingido. (10)",
    30008: "Número máximo de emojis não animados atingido.",
    30010: "Número máximo de reações atingida. (20)",
    30013: "Número máximo de canais atingido. (500)",
    30018: "Número máximo de emojis animados atingido.",
    30030: "Número máximo de categorias atingido. (5)",
    30033: "Número máximo de membros na thread alcançada (1000)",
    30035: "Número de banimentos de membros sem servidor atingido.",
    30037: "Maximum number of bans fetches has been reached",
    30039: "Número máximo de sticker criados atingido.",
    50007: "Não é possível enviar mensagens para este usuário.",
    50008: "Não é possível enviar mensagens em um canal que não seja de texto.",
    50013: "Permissões não suficiente.",
    50028: "Cargo inválido.",
    50034: "As mensagens acima são muito antigadas para deletar.",
    50074: "Não é possível deletar canais configurados pela comunidade do servidor.",
    50080: "Não é possível editar um sticker dentro de uma mensagem.",
    50081: "Um sticker inválido foi enviado.",

    InteractionAlreadyReplied: "Esta interação já foi respondida."
};

export const DiscordErrorsMessage = {
    ClientInvalidOption: "Discord.Errors.ClientInvalidOption",
    ClientInvalidProvidedShards: "Discord.Errors.ClientInvalidProvidedShards",
    ClientMissingIntents: "Discord.Errors.ClientMissingIntents",
    ClientNotReady: "Discord.Errors.ClientNotReady",
    TokenInvalid: "Discord.Errors.TokenInvalid",
    TokenMissing: "Discord.Errors.TokenMissing",
    ApplicationCommandPermissionsTokenMissing: "Discord.Errors.ApplicationCommandPermissionsTokenMissing",
    WSCloseRequested: "Discord.Errors.WSCloseRequested",
    WSConnectionExists: "Discord.Errors.WSConnectionExists",
    WSNotOpen: "Discord.Errors.WSNotOpen",
    ManagerDestroyed: "Discord.Errors.ManagerDestroyed",
    BitFieldInvalid: "Discord.Errors.BitFieldInvalid",
    ShardingInvalid: "Discord.Errors.ShardingInvalid",
    ShardingRequired: "Discord.Errors.ShardingRequired",
    InvalidIntents: "Discord.Errors.InvalidIntents",
    DisallowedIntents: "Discord.Errors.DisallowedIntents",
    ShardingNoShards: "Discord.Errors.ShardingNoShards",
    ShardingInProcess: "Discord.Errors.ShardingInProcess",
    ShardingInvalidEvalBroadcast: "Discord.Errors.ShardingInvalidEvalBroadcast",
    ShardingShardNotFound: "Discord.Errors.ShardingShardNotFound",
    ShardingAlreadySpawned: "Discord.Errors.ShardingAlreadySpawned",
    ShardingProcessExists: "Discord.Errors.ShardingProcessExists",
    ShardingWorkerExists: "Discord.Errors.ShardingWorkerExists",
    ShardingReadyTimeout: "Discord.Errors.ShardingReadyTimeout",
    ShardingReadyDisconnected: "Discord.Errors.ShardingReadyDisconnected",
    ShardingReadyDied: "Discord.Errors.ShardingReadyDied",
    ShardingNoChildExists: "Discord.Errors.ShardingNoChildExists",
    ShardingShardMiscalculation: "Discord.Errors.ShardingShardMiscalculation",
    ColorRange: "Discord.Errors.ColorRange",
    ColorConvert: "Discord.Errors.ColorConvert",
    InviteOptionsMissingChannel: "Discord.Errors.InviteOptionsMissingChannel",
    ButtonLabel: "Discord.Errors.ButtonLabel",
    ButtonURL: "Discord.Errors.ButtonURL",
    ButtonCustomId: "Discord.Errors.ButtonCustomId",
    SelectMenuCustomId: "Discord.Errors.SelectMenuCustomId",
    SelectMenuPlaceholder: "Discord.Errors.SelectMenuPlaceholder",
    SelectOptionLabel: "Discord.Errors.SelectOptionLabel",
    SelectOptionValue: "Discord.Errors.SelectOptionValue",
    SelectOptionDescription: "Discord.Errors.SelectOptionDescription",
    InteractionCollectorError: "Discord.Errors.InteractionCollectorError",
    FileNotFound: "Discord.Errors.FileNotFound",
    UserBannerNotFetched: "Discord.Errors.UserBannerNotFetched",
    UserNoDMChannel: "Discord.Errors.UserNoDMChannel",
    VoiceNotStageChannel: "Discord.Errors.VoiceNotStageChannel",
    VoiceStateNotOwn: "Discord.Errors.VoiceStateNotOwn",
    VoiceStateInvalidType: "Discord.Errors.VoiceStateInvalidType",
    ReqResourceType: "Discord.Errors.ReqResourceType",
    ImageFormat: "Discord.Errors.ImageFormat",
    ImageSize: "Discord.Errors.ImageSize",
    MessageBulkDeleteType: "Discord.Errors.MessageBulkDeleteType",
    MessageNonceType: "Discord.Errors.MessageNonceType",
    MessageContentType: "Discord.Errors.MessageContentType",
    SplitMaxLen: "Discord.Errors.SplitMaxLen",
    BanResolveId: "Discord.Errors.BanResolveId",
    FetchBanResolveId: "Discord.Errors.FetchBanResolveId",
    PruneDaysType: "Discord.Errors.PruneDaysType",
    GuildChannelResolve: "Discord.Errors.GuildChannelResolve",
    GuildVoiceChannelResolve: "Discord.Errors.GuildVoiceChannelResolve",
    GuildChannelOrphan: "Discord.Errors.GuildChannelOrphan",
    GuildChannelUnowned: "Discord.Errors.GuildChannelUnowned",
    GuildOwned: "Discord.Errors.GuildOwned",
    GuildMembersTimeout: "Discord.Errors.GuildMembersTimeout",
    GuildUncachedMe: "Discord.Errors.GuildUncachedMe",
    ChannelNotCached: "Discord.Errors.ChannelNotCached",
    StageChannelResolve: "Discord.Errors.StageChannelResolve",
    GuildScheduledEventResolve: "Discord.Errors.GuildScheduledEventResolve",
    FetchOwnerId: "Discord.Errors.FetchOwnerId",
    InvalidType: "Discord.Errors.InvalidType",
    InvalidElement: "Discord.Errors.InvalidElement",
    MessageThreadParent: "Discord.Errors.MessageThreadParent",
    MessageExistingThread: "Discord.Errors.MessageExistingThread",
    ThreadInvitableType: "Discord.Errors.ThreadInvitableType",
    WebhookMessage: "Discord.Errors.WebhookMessage",
    WebhookTokenUnavailable: "Discord.Errors.WebhookTokenUnavailable",
    WebhookURLInvalid: "Discord.Errors.WebhookURLInvalid",
    WebhookApplication: "Discord.Errors.WebhookApplication",
    MessageReferenceMissing: "Discord.Errors.MessageReferenceMissing",
    EmojiType: "Discord.Errors.EmojiType",
    EmojiManaged: "Discord.Errors.EmojiManaged",
    MissingManageGuildExpressionsPermission: "Discord.Errors.MissingManageGuildExpressionsPermission",
    MissingManageEmojisAndStickersPermission: "Discord.Errors.MissingManageEmojisAndStickersPermission",
    NotGuildSticker: "Discord.Errors.NotGuildSticker",
    ReactionResolveUser: "Discord.Errors.ReactionResolveUser",
    VanityURL: "Discord.Errors.VanityURL",
    InviteResolveCode: "Discord.Errors.InviteResolveCode",
    InviteNotFound: "Discord.Errors.InviteNotFound",
    DeleteGroupDMChannel: "Discord.Errors.DeleteGroupDMChannel",
    FetchGroupDMChannel: "Discord.Errors.FetchGroupDMChannel",
    MemberFetchNonceLength: "Discord.Errors.MemberFetchNonceLength",
    GlobalCommandPermissions: "Discord.Errors.GlobalCommandPermissions",
    GuildUncachedEntityResolve: "Discord.Errors.GuildUncachedEntityResolve",
    InteractionAlreadyReplied: "Discord.Errors.InteractionAlreadyReplied",
    InteractionNotReplied: "Discord.Errors.InteractionNotReplied",
    InteractionEphemeralReplied: "Discord.Errors.InteractionEphemeralReplied",
    CommandInteractionOptionNotFound: "Discord.Errors.CommandInteractionOptionNotFound",
    CommandInteractionOptionType: "Discord.Errors.CommandInteractionOptionType",
    CommandInteractionOptionEmpty: "Discord.Errors.CommandInteractionOptionEmpty",
    CommandInteractionOptionNoSubcommand: "Discord.Errors.CommandInteractionOptionNoSubcommand",
    CommandInteractionOptionNoSubcommandGroup: "Discord.Errors.CommandInteractionOptionNoSubcommandGroup",
    CommandInteractionOptionInvalidChannelType: "Discord.Errors.CommandInteractionOptionInvalidChannelType",
    AutocompleteInteractionOptionNoFocusedOption: "Discord.Errors.AutocompleteInteractionOptionNoFocusedOption",
    ModalSubmitInteractionFieldNotFound: "Discord.Errors.ModalSubmitInteractionFieldNotFound",
    ModalSubmitInteractionFieldType: "Discord.Errors.ModalSubmitInteractionFieldType",
    InvalidMissingScopes: "Discord.Errors.InvalidMissingScopes",
    InvalidScopesWithPermissions: "Discord.Errors.InvalidScopesWithPermissions",
    NotImplemented: "Discord.Errors.NotImplemented",
    SweepFilterReturn: "Discord.Errors.SweepFilterReturn",
    GuildForumMessageRequired: "Discord.Errors.GuildForumMessageRequired",
};

export const PunishmentReasons = [
    "Atividade suspeita.",
    "Spam.",
    "Conta comprometida/hackeada.",
    "Comportamento desrespeitoso.",
    "Quebrou uma ou mais regras do servidor.",
    "Compartilhamento de links suspeitos/maliciosos.",
    "Divulgação inapropriada.",
    "Uso de vocabulário inaprópriado.",
    "Preconceito de raça, genero e/ou cor.",
    "Insubordinação para com os administradores.",
    "Fuga de tópico com frequência.",
    "Conteúdo inapropriado.",
    "Perturbação da paz.",
    "Não atende a idade mínima.",
    "Uso inadequado de mensagens/imagens em canais de texto.",
    "Uso inapropriado dos canais de voz.",
    "Reações desnecessárias em mensagens de canais de texto.",
    "Nome de usuário inadequado.",
    "Avatar de perfil inadequado."
];

export const GuildFeatures = {
    /**
     * Guild has access to set an animated guild banner image
     */
    AnimatedBanner: "ANIMATED_BANNER",
    /**
     * Guild has access to set an animated guild icon
     */
    AnimatedIcon: "ANIMATED_ICON",
    /**
     * Guild is using the old permissions configuration behavior
     *
     * See https://discord.com/developers/docs/change-log#upcoming-application-command-permission-changes
     */
    ApplicationCommandPermissionsV2: "APPLICATION_COMMAND_PERMISSIONS_V2",
    /**
     * Guild has set up auto moderation rules
     */
    AutoModeration: "AUTO_MODERATION",
    /**
     * Guild has access to set a guild banner image
     */
    Banner: "BANNER",
    /**
     * Guild can enable welcome screen, Membership Screening and discovery, and receives community updates
     */
    Community: "COMMUNITY",
    /**
     * Guild has enabled monetization
     */
    CreatorMonetizableProvisional: "CREATOR_MONETIZABLE_PROVISIONAL",
    /**
     * Guild has enabled the role subscription promo page
     */
    CreatorStorePage: "CREATOR_STORE_PAGE",
    DeveloperSupportServer: "DEVELOPER_SUPPORT_SERVER",
    /**
     * Guild is able to be discovered in the directory
     */
    Discoverable: "DISCOVERABLE",
    /**
     * Guild is able to be featured in the directory
     */
    Featurable: "FEATURABLE",
    /**
     * Guild is listed in a directory channel
     */
    HasDirectoryEntry: "HAS_DIRECTORY_ENTRY",
    /**
     * Guild is a Student Hub
     *
     * See https://support.discord.com/hc/articles/4406046651927
     *
     * @unstable This feature is currently not documented by Discord, but has known value
     */
    Hub: "HUB",
    /**
     * Guild has disabled invite usage, preventing users from joining
     */
    InvitesDisabled: "INVITES_DISABLED",
    /**
     * Guild has access to set an invite splash background
     */
    InviteSplash: "INVITE_SPLASH",
    /**
     * Guild is in a Student Hub
     *
     * See https://support.discord.com/hc/articles/4406046651927
     *
     * @unstable This feature is currently not documented by Discord, but has known value
     */
    LinkedToHub: "LINKED_TO_HUB",
    /**
     * Guild has enabled Membership Screening
     */
    MemberVerificationGateEnabled: "MEMBER_VERIFICATION_GATE_ENABLED",
    /**
     * Guild has enabled monetization
     *
     * @unstable This feature is no longer documented by Discord
     */
    MonetizationEnabled: "MONETIZATION_ENABLED",
    /**
     * Guild has increased custom sticker slots
     */
    MoreStickers: "MORE_STICKERS",
    /**
     * Guild has access to create news channels
     */
    News: "NEWS",
    /**
     * Guild is partnered
     */
    Partnered: "PARTNERED",
    /**
     * Guild can be previewed before joining via Membership Screening or the directory
     */
    PreviewEnabled: "PREVIEW_ENABLED",
    /**
     * Guild has access to create private threads
     */
    PrivateThreads: "PRIVATE_THREADS",
    RelayEnabled: "RELAY_ENABLED",
    /**
     * Guild is able to set role icons
     */
    RoleIcons: "ROLE_ICONS",
    /**
     * Guild has role subscriptions that can be purchased
     */
    RoleSubscriptionsAvailableForPurchase: "ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE",
    /**
     * Guild has enabled role subscriptions
     */
    RoleSubscriptionsEnabled: "ROLE_SUBSCRIPTIONS_ENABLED",
    /**
     * Guild has enabled ticketed events
     */
    TicketedEventsEnabled: "TICKETED_EVENTS_ENABLED",
    /**
     * Guild has access to set a vanity URL
     */
    VanityURL: "VANITY_URL",
    /**
     * Guild is verified
     */
    Verified: "VERIFIED",
    /**
     * Guild has access to set 384kbps bitrate in voice (previously VIP voice servers)
     */
    VIPRegions: "VIP_REGIONS",
    /**
     * Guild has enabled the welcome screen
     */
    WelcomeScreenEnabled: "WELCOME_SCREEN_ENABLED",
    /**
     * Not Documented
     */
    ThreeDayThreadArchive: "THREE_DAY_THREAD_ARCHIVE",
    TextInVoiceEnabled: "TEXT_IN_VOICE_ENABLED",
    GuildWebPageVanityUrl: "GUILD_WEB_PAGE_VANITY_URL",
    RaidAlertsEnabled: "RAID_ALERTS_ENABLED",
    EnabledDiscoverableBefore: "ENABLED_DISCOVERABLE_BEFORE",
    SevenDayThreadArchive: "SEVEN_DAY_THREAD_ARCHIVE",
    GuildOndoardingEverEnabled: "GUILD_ONBOARDING_EVER_ENABLED",
    CommunityExpLargeUngated: "COMMUNITY_EXP_LARGE_UNGATED",
    GuildOnboardingHasPrompts: "GUILD_ONBOARDING_HAS_PROMPTS",
    GuildOnboarding: "GUILD_ONBOARDING",
    NewThreadPermissions: "NEW_THREAD_PERMISSIONS",
    ThreadsEnabled: "THREADS_ENABLED",
    MemberProfiles: "MEMBER_PROFILES"
};

export const GuildFeaturesTranslate = {
    ANIMATED_BANNER: "Banner Animado",
    ANIMATED_ICON: "Icone Animado",
    APPLICATION_COMMAND_PERMISSIONS_V2: "Configuração Antigas em Uso",
    AUTO_MODERATION: "AutoMod Ativado",
    BANNER: "Banner Imagem",
    COMMUNITY: "Comunidade",
    CREATOR_MONETIZABLE_PROVISIONAL: "Monetização de Criador",
    CREATOR_STORE_PAGE: "Página de Promoção",
    DEVELOPER_SUPPORT_SERVER: "Servidor de Suporte de Desenvolvedor",
    DISCOVERABLE: "Descobrir Habilitado",
    FEATURABLE: "Pode ser Apresentado em Descobrir",
    HAS_DIRECTORY_ENTRY: "Possui Canal de Diretório",
    HUB: "Hub de Estudantes",
    INVITES_DISABLED: "Convites Desabilitados",
    INVITE_SPLASH: "Imagem de Convite",
    LINKED_TO_HUB: "Linkado ao Hub de Estudantes",
    MEMBER_VERIFICATION_GATE_ENABLED: "Painel de Boas-Vindas",
    MONETIZATION_ENABLED: "Monetização Ativada",
    MORE_STICKERS: "Limite de Stickers Melhorado",
    NEWS: "Pode Criar Canais de Notícias",
    PARTNERED: "Parceiro do Discord",
    PREVIEW_ENABLED: "Visualizar Servidor Antes de Entrar",
    PRIVATE_THREADS: "Criação de Threads",
    RelayEnabled: "Retransmitir Ativado",
    ROLE_ICONS: "Ícones em Cargos",
    GUESTS_ENABLED: "Convidados Ativados",
    ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE: "Itens a Ser Comprados",
    ROLE_SUBSCRIPTIONS_ENABLED: "Itens a Ser Vendidos Ativado",
    TICKETED_EVENTS_ENABLED: "Eventos com Ingressos Ativados",
    VANITY_URL: "URL de Vaidade",
    VERIFIED: "Servidor Verificado",
    VIP_REGIONS: "Regiões VIP",
    WELCOME_SCREEN_ENABLED: "Tela de Boas Vindas",
    THREE_DAY_THREAD_ARCHIVE: "Arquivos de Tópicos de 3 Dias",
    TEXT_IN_VOICE_ENABLED: "Textos em Canais de Voz",
    GUILD_WEB_PAGE_VANITY_URL: "Link de Servidor na WEB",
    RAID_ALERTS_ENABLED: "Alertas de RAID Ativado",
    ENABLED_DISCOVERABLE_BEFORE: "Descobrir Antes Ativado",
    SEVEN_DAY_THREAD_ARCHIVE: "Arquivos de Tópicos de 7 Dias",
    GUILD_ONBOARDING_EVER_ENABLED: "Integração de Servidor Ativada",
    COMMUNITY_EXP_LARGE_UNGATED: "Grande Experiência Comunitária Sem Garantia",
    GUILD_ONBOARDING_HAS_PROMPTS: "Integração de Servidor Possui Prompts",
    SOUNDBOARD: "Painel de Sons",
    GUILD_SERVER_GUIDE: "Guia do Servidor Ativado",
    GUILD_ONBOARDING: "Integração de Servidor",
    NEW_THREAD_PERMISSIONS: "Permissão de Novas Threads",
    THREADS_ENABLED: "Threads Ativada",
    MEMBER_PROFILES: "Perfil de Membros",
    CHANNEL_ICON_EMOJIS_GENERATED: "Icones de Emojis em Canais Gerados"
};

export const locales = {
    "id": "Indonésio",
    "en-US": "Inglês Americano",
    "en-GB": "Inglês Britânico",
    "bg": "Búlgaro",
    "zh-CN": "Chinês",
    "zh-TW": "Mandarim",
    "hr": "Croata",
    "cs": "Tcheco",
    "da": "Dinamarquês",
    "nl": "Holandês",
    "fi": "Finlandês",
    "fr": "Francês",
    "de": "Alemão",
    "el": "Grécia",
    "hi": "Hindi",
    "hu": "Húngaro",
    "it": "Italiano",
    "ja": "Japonês",
    "ko": "Coreano",
    "lt": "Lituano",
    "no": "Norueguês",
    "pl": "Polonês",
    "pt-BR": "Português Brasil",
    "pt-PT": "Português Portugal",
    "ro": "Romeno",
    "ru": "Russo",
    "es-ES": "Espanhol Espanha",
    "sv-SE": "Sueco",
    "th": "Tailandês",
    "tr": "Turco",
    "uk": "Ucraniano",
    "vi": "Vietnamita",
};

export const JokempoValues = [100, 500, 700, 1000, 1500, 2000, 5000, 7000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 50000, 100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 1000000];

export const TwitchLanguages = {
    "aa": "Afar",
    "ab": "Abkhazian",
    "ae": "Avestan",
    "af": "Afrikaans",
    "ak": "Akan",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "as": "Assamese",
    "av": "Avaric",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "ba": "Bashkir",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bh": "Bihari languages",
    "bi": "Bislama",
    "bm": "Bambara",
    "bn": "Bengali",
    "bo": "Tibetan",
    "br": "Breton",
    "bs": "Bosnian",
    "ca": "Catalan",
    "ce": "Chechen",
    "ch": "Chamorro",
    "co": "Corsican",
    "cr": "Cree",
    "cs": "Czech",
    "cu": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "dv": "Divehi; Dhivehi; Maldivian",
    "dz": "Dzongkha",
    "ee": "Ewe",
    "el": "Modern Greek (1453-)",
    "en": "English",
    "eo": "Esperanto",
    "es": "Spanish; Castilian",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "ff": "Fulah",
    "fi": "Finnish",
    "fj": "Fijian",
    "fo": "Faroese",
    "fr": "French",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gd": "Gaelic; Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gu": "Gujarati",
    "gv": "Manx",
    "ha": "Hausa",
    "he": "Hebrew",
    "hi": "Hindi",
    "ho": "Hiri Motu",
    "hr": "Croatian",
    "ht": "Haitian; Haitian Creole",
    "hu": "Hungarian",
    "hy": "Armenian",
    "hz": "Herero",
    "ia": "Interlingua (International Auxiliary Language Association)",
    "id": "Indonesian",
    "ie": "Interlingue; Occidental",
    "ig": "Igbo",
    "ii": "Sichuan Yi; Nuosu",
    "ik": "Inupiaq",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "iu": "Inuktitut",
    "ja": "Japanese",
    "jv": "Javanese",
    "ka": "Georgian",
    "kg": "Kongo",
    "ki": "Kikuyu; Gikuyu",
    "kj": "Kuanyama; Kwanyama",
    "kk": "Kazakh",
    "kl": "Greenlandic; Kalaallisut",
    "km": "Central Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "kr": "Kanuri",
    "ks": "Kashmiri",
    "ku": "Kurdish",
    "kv": "Komi",
    "kw": "Cornish",
    "ky": "Kirghiz; Kyrgyz",
    "la": "Latin",
    "lb": "Luxembourgish; Letzeburgesch",
    "lg": "Ganda",
    "li": "Limburgish; Limburgan; Limburger",
    "ln": "Lingala",
    "lo": "Lao",
    "lt": "Lithuanian",
    "lu": "Luba-Katanga",
    "lv": "Latvian",
    "mg": "Malagasy",
    "mh": "Marshallese",
    "mi": "Maori",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "ms": "Malay",
    "mt": "Maltese",
    "my": "Burmese; Myanmar",
    "na": "Nauruan",
    "nb": "Norwegian Bokmål",
    "nd": "North Ndebele",
    "ne": "Nepali",
    "ng": "Ndonga",
    "nl": "Dutch; Flemish",
    "nn": "Norwegian Nynorsk",
    "no": "Norwegian",
    "nr": "South Ndebele",
    "nv": "Navajo; Navaho",
    "ny": "Chichewa; Chewa; Nyanja",
    "oc": "Occitan (post-1500)",
    "oj": "Ojibwa",
    "om": "Oromo",
    "or": "Oriya",
    "os": "Ossetian; Ossetic",
    "pa": "Punjabi; Panjabi",
    "pi": "Pali",
    "pl": "Polish",
    "ps": "Pashto; Pushto",
    "pt": "Portuguese",
    "qu": "Quechua",
    "rm": "Romansh",
    "rn": "Rundi",
    "ro": "Romanian; Moldavian; Moldovan",
    "ru": "Russian",
    "rw": "Kinyarwanda; Rwandese",
    "sa": "Sanskrit",
    "sc": "Sardinian",
    "sd": "Sindhi",
    "se": "Northern Sami",
    "sg": "Sango",
    "si": "Sinhala; Sinhalese",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sm": "Samoan",
    "sn": "Shona",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "ss": "Swati",
    "st": "Southern Sotho",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "ti": "Tigrinya",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tn": "Tswana",
    "to": "Tonga (Tonga Islands)",
    "tr": "Turkish",
    "ts": "Tsonga",
    "tt": "Tatar",
    "tw": "Twi",
    "ty": "Tahitian",
    "ug": "Uighur; Uyghur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "ve": "Venda",
    "vi": "Vietnamese",
    "vo": "Volapük",
    "wa": "Walloon",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "za": "Zhuang; Chuang",
    "zh": "Chinese",
    "zu": "Zulu"
};

export const NSFWImagesCategory = [
    "anal",
    "ass",
    "bdsm",
    "cum",
    "classic",
    "creampie",
    "manga",
    "femdom",
    "hentai",
    "incest",
    "masturbation",
    "public",
    "ero",
    "orgy",
    "elves",
    "yuri",
    "pantsu",
    "glasses",
    "cuckold",
    "blowjob",
    "boobjob",
    // "footjoob",
    "handjoob",
    "boobs",
    "thighs",
    "pussy",
    "ahegao",
    "gangbang",
    "tentacles",
    "uniform",
    "gif",
    "nsfwNeko",
    "nsfwMobileWallpaper",
    "zettaiRyouiki",

    // NekoBot
    "paizuri",
    "hanal",
    "kitsune",
    "lewdneko",
    "tentacle",

    // Nekos
    "wallpaper"
];

export const ChannelsInGame = new Set<string>();

export const StaffsIDs = {
    Rody: "451619591320371213",
    Gowther: "315297741406339083",
    Makol: "351903530161799178",
    Moana: "737238491842347098",
    Dspofu: "781137239194468403",
    Pepy: "830226550116057149",
    Lereo: "978659462602711101",
    San: "327496267007787008",
    Khetlyn: "428088706533031938",
    Yafyr: "435444989695229952",
    Andre: "648389538703736833",
    Pandinho: "1090693149778772088",
    Gorniaky: "395669252121821227",
    Mari: "704023863314350081",
    Lewd: "140926143783108610"
};

export const buttonsPagination = {
    type: 1,
    components: [
        {
            type: 2,
            label: "⏪",
            custom_id: "zero",
            style: ButtonStyle.Primary
        },
        {
            type: 2,
            label: "⬅️",
            custom_id: "preview",
            style: ButtonStyle.Primary
        },
        {
            type: 2,
            label: "➡️",
            custom_id: "next",
            style: ButtonStyle.Primary
        },
        {
            type: 2,
            label: "⏩",
            custom_id: "last",
            style: ButtonStyle.Primary
        }
    ]
};