import { ApplicationCommandOptionType, ApplicationCommandType, ChannelType, ChatInputCommandInteraction, PermissionFlagsBits, PermissionsBitField } from "discord.js";
import client from "../../../saphire";
import { getLocalizations } from "../../../util/getlocalizations";
import { DiscordPermissons } from "../../../util/constants";
import permissionsMissing from "../../functions/permissionsMissing";
import clear from "../../functions/clear/clear";

/**
 * https://discord.com/developers/docs/interactions/application-commands#application-command-object
 * https://discord.com/developers/docs/reference#locales
 * "id" and "version" not used here
 */
export default {
    data: {
        type: ApplicationCommandType.ChatInput,
        application_id: client.user?.id,
        guild_id: "",
        name: "clear",
        name_localizations: getLocalizations("clear.name"),
        description: "[moderation] Clear the channel's message (0~1000)",
        description_localizations: getLocalizations("clear.description"),
        default_member_permissions: PermissionsBitField.Flags.ManageMessages.toString(),
        dm_permission: false,
        nsfw: false,
        options: [
            {
                name: "amount",
                name_localizations: getLocalizations("clear.options.0.name"),
                description: "Amount of messages to be deleted (1~1000)",
                description_localizations: getLocalizations("clear.options.0.description"),
                type: ApplicationCommandOptionType.Integer,
                min_value: 1,
                max_value: 1000,
                required: true,
            },
            {
                name: "members",
                name_localizations: getLocalizations("clear.options.1.name"),
                description: "Filter: Select a member to clear their messages",
                description_localizations: getLocalizations("clear.options.1.description"),
                type: ApplicationCommandOptionType.String,
            },
            {
                name: "channel",
                name_localizations: getLocalizations("clear.options.2.name"),
                description: "Filter: Select a channel to clear their messages",
                description_localizations: getLocalizations("clear.options.2.description"),
                type: ApplicationCommandOptionType.Channel,
                channel_types: [
                    ChannelType.AnnouncementThread,
                    ChannelType.GuildAnnouncement,
                    ChannelType.GuildForum,
                    ChannelType.GuildStageVoice,
                    ChannelType.GuildText,
                    ChannelType.GuildVoice,
                    ChannelType.PrivateThread,
                    ChannelType.PublicThread,
                ],
            },
            {
                name: "filter",
                name_localizations: getLocalizations("clear.options.3.name"),
                description: "Apply more filters",
                description_localizations: getLocalizations("clear.options.3.description"),
                type: ApplicationCommandOptionType.String,
                choices: [
                    {
                        name: "Clear only bot's message",
                        name_localizations: getLocalizations("clear.options.3.choices.0"),
                        value: "bots",
                    },
                    {
                        name: "Clear messages with files/photos/videos/gifs...",
                        name_localizations: getLocalizations("clear.options.3.choices.1"),
                        value: "attachments",
                    },
                    {
                        name: "Clear only webhook's message",
                        name_localizations: getLocalizations("clear.options.3.choices.2"),
                        value: "webhooks",
                    },
                    {
                        name: "ignore bot's message",
                        name_localizations: getLocalizations("clear.options.3.choices.3"),
                        value: "ignoreBots",
                    },
                    {
                        name: "Ignore member's message",
                        name_localizations: getLocalizations("clear.options.3.choices.4"),
                        value: "ignoreMembers",
                    },
                    {
                        name: "Ignore webhook's message",
                        name_localizations: getLocalizations("clear.options.3.choices.5"),
                        value: "ignoreWebhooks",
                    },
                ],
            },
            {
                name: "script",
                name_localizations: getLocalizations("clear.options.4.name"),
                description: "Get a TXT file with all data generated by this command",
                description_localizations: getLocalizations("clear.options.4.description"),
                type: ApplicationCommandOptionType.String,
                choices: [
                    {
                        name: "Yes, i want this file",
                        name_localizations: getLocalizations("clear.options.4.choices.0"),
                        value: "script",
                    },
                ],
            },
        ],
    },
    additional: {
        category: "moderation",
        admin: false,
        staff: false,
        api_data: {
            description: "Clear the channel's message",
            category: "Moderação",
            synonyms: [],
            tags: [],
            perms: {
                user: [DiscordPermissons.ManageMessages],
                bot: [DiscordPermissons.ReadMessageHistory, DiscordPermissons.ManageMessages],
            },
        },
        async execute(interaction: ChatInputCommandInteraction<"cached">) {

            const { guild, member } = interaction;

            if (!member?.permissions.has([PermissionFlagsBits.ReadMessageHistory, PermissionFlagsBits.ManageMessages], true))
                return await permissionsMissing(interaction, [DiscordPermissons.ReadMessageHistory, DiscordPermissons.ManageMessages], "Discord_you_need_some_permissions");

            if (!guild.members.me?.permissions.has([PermissionFlagsBits.ReadMessageHistory, PermissionFlagsBits.ManageMessages], true))
                return await permissionsMissing(interaction, [DiscordPermissons.ReadMessageHistory, DiscordPermissons.ManageMessages], "Discord_client_need_some_permissions");

            return await clear(interaction);

        },
    },
};